# Generated by Django 5.2.3 on 2025-07-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=2),
        ),
    ]
