# Generated by Django 5.2.3 on 2025-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
