# Generated by Django 5.2.3 on 2025-07-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_album_rating_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='rating_enabled',
            new_name='ratings_enabled',
        ),
    ]
