# Generated by Django 5.2.3 on 2025-07-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_track_price'),
        ('store', '0007_rename_rating_enabled_album_ratings_enabled'),
    ]

    operations = [
    ]
