# 
image: python:3.13.5

#variables:

stages: 
  - test 
  - build
#  - deploy

#build-job:
  #stage: build


test-job: 
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py check

docker-build:
  stage: build

  image: docker:20.10.16
  services:
    - name: registry.hub.docker.com/library/docker:20.10.16-dind
      alias: docker
  tags:
    - docker-privileged
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/jala5026/pywebshop25:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY/jala5026/pywebshop25:$CI_COMMIT_REF_SLUG

