# Generated by Django 5.2.3 on 2025-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[('SU', 'superuser'), ('CS', 'customer service'), ('CU', 'customer')], default='CU', max_length=2),
        ),
    ]
