# Generated by Django 5.2.3 on 2025-07-13 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0002_myuser_profile_picture_myuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2007, 7, 13)),
        ),
    ]
